### ISSUE TITLE
crash with the pickaxe

### ISSUE THREAD

**Issue by Zack7292** [transfarmer/adventure-items#7]
when i made my pickaxe mine his first block i got this crash:
https://pastebin.com/GpB2AEcX

**Comment by nnym** [comment]
I (think that I) did not fix this bug because I was unable to reproduce it; however, I made some other fixes and set the game to not crash when it happens, so if you see anything strange about item tooltips, then check your log and open another issue. I will upload the "fix" to CurseForge in a few minutes.

**Comment by Zack7292** [comment]
ok thx :)
